### PR TITLE
Fix markdownlint

### LINKED ISSUE #4: Action creates an empty report
The job outputs the findings of markdownlint, but the report by reviewdog does not contain any finding.

Example:
https://github.com/Rotzbua/test_markdownlint/runs/1625711973

### PR DESCRIPTION
**Pull request by haya14busa**
Fix #4 .... or I'd say fix the action completely.

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -4,10 +4,5 @@ cd "${GITHUB_WORKSPACE}" || exit
...
 
-if [ "${INPUT_REPORTER}" = x"github-pr-review" ]; then
-  markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" |
-    reviewdog -efm="%s:%l:%c %m" -name="markdownlint" -diff="git diff HEAD^" -reporter=github-pr-review -level="${INPUT_LEVEL}" -tee
-else
-  markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" |
-    reviewdog -efm="%f:%l:%c %m" -name="markdownlint" -diff="git diff HEAD^" -reporter=github-pr-check -level="${INPUT_LEVEL}" -tee
-fi
+markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" |
+  reviewdog -efm="%f:%l:%c %m" -efm="%f:%l %m" -name="markdownlint" -reporter="${INPUT_REPORTER}" -level="${INPUT_LEVEL}"
```
Comment (skarzi) [inline entrypoint.sh:8]: is it intentional to pass the `-efm` option 2 times?

Comment (haya14busa) [reply entrypoint.sh]: yes. it supports multiple errorformats.

Comment (haya14busa) [reply entrypoint.sh]: Now that you mentioned it, we may want to add multiple `-efm` example in reviewdog README.

File: README.md [hunk 2]
```diff
@@ -11,24 +11,36 @@ code review experience.
...
+    description: |
+      Exit code for reviewdog when errors are found [true,false]
+      Default is `false`.
+    default: 'false'
+  reviewdog_flags:
+    description: 'Additional reviewdog flags'
+    default: ''
+  ### Flags for <linter-name> ###
+  markdownlint_flags:
+    description: "Options of markdownlint command. Default: '.'"
```
Comment (skarzi) [inline README.md:41]:
```suggestion
    description: "Options of markdownlint-cli command. Default: '.'"
```

File: README.md [hunk 3]
```diff
@@ -11,24 +11,36 @@ code review experience.
...
+inputs:
+  github_token:
+    description: 'GITHUB_TOKEN.'
+    required: true
+  ### Flags for reviewdog ###
+  level:
+    description: 'Report level for reviewdog [info,warning,error]'
+    default: 'error'
+  reporter:
+    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
```
Comment (skarzi) [inline README.md:24]: Is it possible to easily add `github-check` reporter support?
Personally, I found it most useful to run `markdownlit` on every push

File: action.yml [hunk 4]
```diff
@@ -5,15 +5,27 @@ inputs:
...
+    default: 'added'
+  fail_on_error:
+    description: |
+      Exit code for reviewdog when errors are found [true,false]
+      Default is `false`.
+    default: 'false'
+  reviewdog_flags:
+    description: 'Additional reviewdog flags'
+    default: ''
+  ### Flags for <linter-name> ###
```
Comment (skarzi) [inline action.yml:28]:
```suggestion
  ### Flags for markdownlint-cli ###
```

File: action.yml [hunk 5]
```diff
@@ -5,15 +5,27 @@ inputs:
...
   markdownlint_flags:
     description: "Options of markdownlint command. Default: '.'"
```
Comment (skarzi) [inline action.yml:30]:
```suggestion
    description: "Options of markdownlint-cli command. Default: '.'"
```

File: entrypoint.sh [hunk 6]
```diff
@@ -4,10 +4,13 @@ cd "${GITHUB_WORKSPACE}" || exit
...
 
-if [ "${INPUT_REPORTER}" = x"github-pr-review" ]; then
-  markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" |
-    reviewdog -efm="%s:%l:%c %m" -name="markdownlint" -diff="git diff HEAD^" -reporter=github-pr-review -level="${INPUT_LEVEL}" -tee
-else
-  markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" |
-    reviewdog -efm="%f:%l:%c %m" -name="markdownlint" -diff="git diff HEAD^" -reporter=github-pr-check -level="${INPUT_LEVEL}" -tee
-fi
+markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" |
+  reviewdog \
```
Comment (skarzi) [inline entrypoint.sh]: shouldn't this line also end with `/`?

```suggestion
markdownlint "${INPUT_MARKDOWNLINT_FLAGS:-.}" \
  | reviewdog \
```

File: Dockerfile [hunk 7]
```diff
@@ -1,6 +1,7 @@
 FROM prologic/markdownlint:latest
 
-RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ v0.9.15
+RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
+    | sh -s -- -b /usr/local/bin/ v0.11.0
```
Comment (skarzi) [inline Dockerfile:4]: we can also use `ENV REVIEWDOG_VERSION=v0.11.0` just to make it easy to add periodic workflow with [`action-depup`](https://github.com/reviewdog/action-depup).
But it can be done in separate PR, what do you think?

File: entrypoint.sh (hunk 6 above)
Comment (haya14busa) [reply entrypoint.sh]: Oh that's good catch. I wonder why it worked as-is.
Probably the bash feature? I'll fix it anyway.

File: README.md (hunk 3 above)
Comment (haya14busa) [reply README.md:24]: Yes. it requires only documentation changes :) Done.

File: Dockerfile (hunk 7 above)
Comment (haya14busa) [reply Dockerfile:4]: Yes. That's good point. I plan to create a separate PR.

**Review by skarzi — APPROVED** [review]
great work!

**Comment by haya14busa** [comment]
Thank you for your work :)
